name: Fly me to the moon
run-name: ${{ github.actor }} is shipping magic numbers to the moon 🚀🌙✨
on:
  push:
    branches: [ 'main', 'action' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Run yarn install
        uses: borales/actions-yarn@v5
        with:
          cmd: install
      - name: run yarn build
        uses: borales/actions-yarn@v5
        with:
          cmd: build

      - uses: actions/upload-artifact@master
        with:
          name: page
          path: dist
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    steps:
      - name: Set Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - uses: actions/download-artifact@master
        with:
          name: page
          path: .
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - id: deployment
        uses: actions/deploy-pages@main